### ISSUE TITLE
cp missing -r

### ISSUE THREAD

**Issue by mebarton** [vanbwodonk/gcc-arm-embedded-build-armhf#2]
I ran you code but it failed to copy the files to /usr/bin/ found you missed the -r on the cp 
in the "install via raspberry pi terminal:" 
...
sudo cp gcc-arm-none-eabi-8-2019-q3-update/* /usr/

should be this
sudo cp -r gcc-arm-none-eabi-8-2019-q3-update/* /usr/

Thanks for the code it help alot

**Comment by vanbwodonk** [comment]
My bad, Already fixed in https://github.com/vanbwodonk/gcc-arm-embedded-build-armhf/commit/99d3ef6dc8bee4ef50b6d94741bdb47fa0ab1c31. Thank you for positive feedback.
