### ISSUE TITLE
Built unusable on Raspberry Pi 3 with Raspbian GNU/Linux 9

### ISSUE THREAD

**Issue by dl9sec** [vanbwodonk/gcc-arm-embedded-build-armhf#3]
Trying to use your built gives the following error message on my RasPi 3:

`./arm-none-eabi-gcc --version`
`./arm-none-eabi-gcc: /lib/arm-linux-gnueabihf/libc.so.6: version 'GLIBC_2.28' not found (required by ./arm-none-eabi-gcc)`

Raspbian uses GLIBC 2.24:

` ldd --version`
`ldd (Debian GLIBC 2.24-11+deb9u4) 2.24
Copyright © 2016 Free Software Foundation, Inc.
Dies ist freie Software; in den Quellen befinden sich die Lizenzbedingungen.
Es gibt KEINERLEI Garantie; nicht einmal für die TAUGLICHKEIT oder
VERWENDBARKEIT FÜR EINEN ANGEGEBENEN ZWECK.
Implementiert von Roland McGrath und Ulrich Drepper.`

Regards, Thorsten

**Comment by dl9sec** [comment]
Updating from stretch to buster will solve the problem.
See [https://pimylifeup.com/upgrade-raspbian-stretch-to-raspbian-buster/](url)

Regards, Thorsten

**Comment by vanbwodonk** [comment]
Nice info !!! Thanks
